version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Build and Test
                command: ./gradlew clean build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
          destination: reports

  publish-to-jitpack:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Set Build Number
          command: |
            # Use the CircleCI build number directly without additional processing
            echo "export BUILD_NUMBER=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            source $BASH_ENV
            echo "Using build number: ${BUILD_NUMBER}"
      - gradle/with_cache:
          steps:
            - run:
                name: Build with Build Number
                command: ./gradlew clean build -PbuildNumber=${BUILD_NUMBER}
            - run:
                name: Publish to Local Maven Repository
                command: ./gradlew publishToMavenLocal -PbuildNumber=${BUILD_NUMBER}
      - run:
          name: Create and Push Git Tag
          command: |
            # Create a git tag with the version number
            VERSION="1.0.${BUILD_NUMBER}"
            echo "Creating tag for version: ${VERSION}"
            git config user.email "ci@incept5.com"
            git config user.name "CircleCI"
            git tag -a "${VERSION}" -m "Release version ${VERSION}"
            git push origin "${VERSION}"
      - run:
          name: Trigger JitPack Build
          command: |
            VERSION="1.0.${BUILD_NUMBER}"
            
            # Debug information
            echo "Maven repository location: $HOME/.m2/repository"
            echo "Verifying local artifacts:"
            
            # List all error-core and error-quarkus artifacts in the local Maven repository
            echo "All error-core artifacts:"
            find $HOME/.m2/repository -name "error-core*" | sort
            
            echo "All error-quarkus artifacts:"
            find $HOME/.m2/repository -name "error-quarkus*" | sort
            
            # Specifically look for artifacts with the expected version
            echo "Looking for artifacts with version ${VERSION}:"
            find $HOME/.m2/repository -path "*${VERSION}*" | sort
            
            # Check if the expected directories exist
            echo "Checking if expected directories exist:"
            if [ -d "$HOME/.m2/repository/com/github/incept5/error-core/${VERSION}" ]; then
              echo "Directory for error-core exists"
              ls -la "$HOME/.m2/repository/com/github/incept5/error-core/${VERSION}"
            else
              echo "Directory for error-core does not exist"
              # Check parent directory
              echo "Contents of parent directory:"
              ls -la "$HOME/.m2/repository/com/github/incept5/error-core/" || echo "Parent directory does not exist"
            fi
            
            if [ -d "$HOME/.m2/repository/com/github/incept5/error-quarkus/${VERSION}" ]; then
              echo "Directory for error-quarkus exists"
              ls -la "$HOME/.m2/repository/com/github/incept5/error-quarkus/${VERSION}"
            else
              echo "Directory for error-quarkus does not exist"
              # Check parent directory
              echo "Contents of parent directory:"
              ls -la "$HOME/.m2/repository/com/github/incept5/error-quarkus/" || echo "Parent directory does not exist"
            fi
            
            # Republish with explicit version to ensure artifacts are in the correct location
            echo "Republishing artifacts with explicit version ${VERSION}"
            ./gradlew clean build publishToMavenLocal -Pgroup=com.github.incept5 -Pversion=${VERSION}
            
            # Verify that both JARs exist locally after republishing
            if [ ! -f "$HOME/.m2/repository/com/github/incept5/error-core/${VERSION}/error-core-${VERSION}.jar" ]; then
              echo "ERROR: error-core JAR not found locally at expected path"
              echo "Expected: $HOME/.m2/repository/com/github/incept5/error-core/${VERSION}/error-core-${VERSION}.jar"
              # Try to find it elsewhere
              echo "Searching for error-core JAR:"
              find $HOME/.m2/repository -name "error-core-${VERSION}.jar" || echo "No matching JAR found"
              exit 1
            fi
            
            if [ ! -f "$HOME/.m2/repository/com/github/incept5/error-quarkus/${VERSION}/error-quarkus-${VERSION}.jar" ]; then
              echo "ERROR: error-quarkus JAR not found locally at expected path"
              echo "Expected: $HOME/.m2/repository/com/github/incept5/error-quarkus/${VERSION}/error-quarkus-${VERSION}.jar"
              # Try to find it elsewhere
              echo "Searching for error-quarkus JAR:"
              find $HOME/.m2/repository -name "error-quarkus-${VERSION}.jar" || echo "No matching JAR found"
              exit 1
            fi
            
            echo "Both artifacts verified locally"
            
            # Trigger JitPack build by making a request to the JitPack URL with the version tag
            echo "Triggering JitPack build for version ${VERSION}"
            curl -s "https://jitpack.io/com/github/incept5/error-lib/${VERSION}/error-lib-${VERSION}.pom" || true
            
            echo "JitPack build triggered for version ${VERSION}"
            echo "Artifacts will be available at: https://jitpack.io/#com.github.incept5/error-lib/${VERSION}"
            
            # Wait for JitPack to process the build
            echo "Waiting for JitPack to process the build..."
            sleep 120
            
            # Verify the build status for error-core
            CORE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/error-core/${VERSION}/error-core-${VERSION}.jar")
            if [ "$CORE_STATUS" -eq 200 ]; then
              echo "error-core artifact successfully published to JitPack!"
            else
              echo "error-core artifact not found on JitPack. Status code: $CORE_STATUS"
              echo "Check status at: https://jitpack.io/#com.github.incept5/error-lib/${VERSION}"
            fi
            
            # Verify the build status for error-quarkus
            QUARKUS_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/error-quarkus/${VERSION}/error-quarkus-${VERSION}.jar")
            if [ "$QUARKUS_STATUS" -eq 200 ]; then
              echo "error-quarkus artifact successfully published to JitPack!"
            else
              echo "error-quarkus artifact not found on JitPack. Status code: $QUARKUS_STATUS"
              echo "Check status at: https://jitpack.io/#com.github.incept5/error-lib/${VERSION}"
            fi
            
            # Final verification
            if [ "$CORE_STATUS" -eq 200 ] && [ "$QUARKUS_STATUS" -eq 200 ]; then
              echo "Both artifacts successfully published to JitPack!"
            else
              echo "WARNING: One or both artifacts may not be available yet on JitPack."
              echo "This is normal as JitPack may take some time to process the build."
            fi

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-and-test
      - publish-to-jitpack:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
